prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix dct: <http://purl.org/dc/terms/>


CONSTRUCT
{
  ?ontology dct:issued ?date .
  ?ontology a owl:Ontology .
}
WHERE 
{
  ?meta_ontology a owl:Ontology .
  ?meta_ontology dct:issued ?date .
  BIND (IRI(REPLACE(STR(?meta_ontology), "MetadataFIBO/", "quick/")) as ?ontology)
}
