#
# The /etc/bashrc file will be executed for all non-interactive or interactive shells
#

export TMPDIR=/var/tmp

if [ -z "${JAVA_HOME}" ] ; then
  echo "ERROR: JAVA_HOME is empty"
else
  export PATH=${PATH}:${JAVA_HOME}/bin
fi

if [ -z "${JENA_HOME}" ] ; then
  echo "ERROR: JENA_HOME is empty"
else
  export PATH=${PATH}:${JENA_HOME}/bin
fi
