PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX fibo-skos: <https://spec.edmcouncil.org/fibo/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT 
{
    fibo-skos:ClassConcepts a skos:ConceptScheme ;
        rdfs:label "Classes Scheme" ;
        rdfs:comment "The concept scheme for concepts derived from ontology classes".
        fibo-skos:PropertyConcepts a skos:ConceptScheme; rdfs:label "Property Scheme" ;
        rdfs:comment "The concept scheme for concepts derived from ontology properties".
        fibo-skos:rangeRelated a owl:ObjectProperty ; rdfs:subPropertyOf skos:related;
        rdfs:label "Range relationship" ;
        rdfs:comment "Denotes an rdfs:range relationship between concepts" .
        fibo-skos:domainRelated a owl:ObjectProperty ; rdfs:subPropertyOf skos:related;
        rdfs:label "Domain relationship" ;
        rdfs:comment "Denotes an rdfs:domain relationship between concepts" .
}
WHERE
{
}


