name: publish_docker_image

on:
  push:
    branches:
      - "stable"
      - "build-dev"
      - "152-automation-of-docker-image-publication"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: edmcouncil/ontology-publisher
          labels: |
            org.edmcouncil.ontology-publisher.release-date={{date 'YYYY-MM-DD'}}
            org.edmcouncil.ontology-publisher.version={{branch}}
      -
        name: Build and push edmcouncil/ontology-publisher:${{ steps.meta.outputs.version }} for linux/amd64 platform
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: edmcouncil/ontology-publisher:${{ steps.meta.outputs.version }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build and push edmcouncil/ontology-publisher:${{ steps.meta.outputs.version }} for linux/arm64 platform
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: edmcouncil/ontology-publisher:${{ steps.meta.outputs.version }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
